package com.javaone.mybatis.dao;

import com.javaone.mybatis.model.pfmsExpend;
import com.javaone.mybatis.model.pfmsExpendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface pfmsExpendMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int countByExample(pfmsExpendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByExample(pfmsExpendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insert(pfmsExpend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insertSelective(pfmsExpend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	List<pfmsExpend> selectByExample(pfmsExpendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	pfmsExpend selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExampleSelective(@Param("record") pfmsExpend record,
                                 @Param("example") pfmsExpendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExample(@Param("record") pfmsExpend record,
                        @Param("example") pfmsExpendExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKeySelective(pfmsExpend record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_expend
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKey(pfmsExpend record);
}