package com.javaone.mybatis.dao;

import com.javaone.mybatis.model.pfmsSys;
import com.javaone.mybatis.model.pfmsSysExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface pfmsSysMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int countByExample(pfmsSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByExample(pfmsSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByPrimaryKey(String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insert(pfmsSys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insertSelective(pfmsSys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	List<pfmsSys> selectByExample(pfmsSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	pfmsSys selectByPrimaryKey(String sysId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExampleSelective(@Param("record") pfmsSys record,
                                 @Param("example") pfmsSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExample(@Param("record") pfmsSys record,
                        @Param("example") pfmsSysExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKeySelective(pfmsSys record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_sys
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKey(pfmsSys record);
}