package com.javaone.mybatis.dao;

import com.javaone.mybatis.model.pfmsAcc;
import com.javaone.mybatis.model.pfmsAccExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface pfmsAccMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int countByExample(pfmsAccExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByExample(pfmsAccExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByPrimaryKey(String accNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insert(pfmsAcc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insertSelective(pfmsAcc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	List<pfmsAcc> selectByExample(pfmsAccExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	pfmsAcc selectByPrimaryKey(String accNo);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExampleSelective(@Param("record") pfmsAcc record,
                                 @Param("example") pfmsAccExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExample(@Param("record") pfmsAcc record,
                        @Param("example") pfmsAccExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKeySelective(pfmsAcc record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKey(pfmsAcc record);
}