package com.javaone.mybatis.dao;

import com.javaone.mybatis.model.pfmsUser;
import com.javaone.mybatis.model.pfmsUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface pfmsUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int countByExample(pfmsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByExample(pfmsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insert(pfmsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int insertSelective(pfmsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	List<pfmsUser> selectByExample(pfmsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	pfmsUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExampleSelective(@Param("record") pfmsUser record,
                                 @Param("example") pfmsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByExample(@Param("record") pfmsUser record,
                        @Param("example") pfmsUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKeySelective(pfmsUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_user
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	int updateByPrimaryKey(pfmsUser record);
}