package com.javaone.mybatis.model;

import java.util.Date;

public class pfmsUsage1 {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_usage1.ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_usage1.CREATER
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private Integer creater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_usage1.TYPE
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_usage1.NAME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_usage1.CREATE_TIME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_usage1.DESCRIPT
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String descript;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_usage1.ID
	 * @return  the value of pfmsdb_usage1.ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_usage1.ID
	 * @param id  the value for pfmsdb_usage1.ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_usage1.CREATER
	 * @return  the value of pfmsdb_usage1.CREATER
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public Integer getCreater() {
		return creater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_usage1.CREATER
	 * @param creater  the value for pfmsdb_usage1.CREATER
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setCreater(Integer creater) {
		this.creater = creater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_usage1.TYPE
	 * @return  the value of pfmsdb_usage1.TYPE
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_usage1.TYPE
	 * @param type  the value for pfmsdb_usage1.TYPE
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_usage1.NAME
	 * @return  the value of pfmsdb_usage1.NAME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_usage1.NAME
	 * @param name  the value for pfmsdb_usage1.NAME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_usage1.CREATE_TIME
	 * @return  the value of pfmsdb_usage1.CREATE_TIME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_usage1.CREATE_TIME
	 * @param createTime  the value for pfmsdb_usage1.CREATE_TIME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_usage1.DESCRIPT
	 * @return  the value of pfmsdb_usage1.DESCRIPT
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getDescript() {
		return descript;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_usage1.DESCRIPT
	 * @param descript  the value for pfmsdb_usage1.DESCRIPT
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setDescript(String descript) {
		this.descript = descript == null ? null : descript.trim();
	}
}