package com.javaone.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class pfmsAccExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public pfmsAccExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andAccNoIsNull() {
			addCriterion("ACC_NO is null");
			return (Criteria) this;
		}

		public Criteria andAccNoIsNotNull() {
			addCriterion("ACC_NO is not null");
			return (Criteria) this;
		}

		public Criteria andAccNoEqualTo(String value) {
			addCriterion("ACC_NO =", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoNotEqualTo(String value) {
			addCriterion("ACC_NO <>", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoGreaterThan(String value) {
			addCriterion("ACC_NO >", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoGreaterThanOrEqualTo(String value) {
			addCriterion("ACC_NO >=", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoLessThan(String value) {
			addCriterion("ACC_NO <", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoLessThanOrEqualTo(String value) {
			addCriterion("ACC_NO <=", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoLike(String value) {
			addCriterion("ACC_NO like", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoNotLike(String value) {
			addCriterion("ACC_NO not like", value, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoIn(List<String> values) {
			addCriterion("ACC_NO in", values, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoNotIn(List<String> values) {
			addCriterion("ACC_NO not in", values, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoBetween(String value1, String value2) {
			addCriterion("ACC_NO between", value1, value2, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccNoNotBetween(String value1, String value2) {
			addCriterion("ACC_NO not between", value1, value2, "accNo");
			return (Criteria) this;
		}

		public Criteria andAccUseridIsNull() {
			addCriterion("ACC_USERID is null");
			return (Criteria) this;
		}

		public Criteria andAccUseridIsNotNull() {
			addCriterion("ACC_USERID is not null");
			return (Criteria) this;
		}

		public Criteria andAccUseridEqualTo(Integer value) {
			addCriterion("ACC_USERID =", value, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridNotEqualTo(Integer value) {
			addCriterion("ACC_USERID <>", value, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridGreaterThan(Integer value) {
			addCriterion("ACC_USERID >", value, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("ACC_USERID >=", value, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridLessThan(Integer value) {
			addCriterion("ACC_USERID <", value, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridLessThanOrEqualTo(Integer value) {
			addCriterion("ACC_USERID <=", value, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridIn(List<Integer> values) {
			addCriterion("ACC_USERID in", values, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridNotIn(List<Integer> values) {
			addCriterion("ACC_USERID not in", values, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridBetween(Integer value1, Integer value2) {
			addCriterion("ACC_USERID between", value1, value2, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("ACC_USERID not between", value1, value2, "accUserid");
			return (Criteria) this;
		}

		public Criteria andAccNameIsNull() {
			addCriterion("ACC_NAME is null");
			return (Criteria) this;
		}

		public Criteria andAccNameIsNotNull() {
			addCriterion("ACC_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andAccNameEqualTo(String value) {
			addCriterion("ACC_NAME =", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameNotEqualTo(String value) {
			addCriterion("ACC_NAME <>", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameGreaterThan(String value) {
			addCriterion("ACC_NAME >", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameGreaterThanOrEqualTo(String value) {
			addCriterion("ACC_NAME >=", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameLessThan(String value) {
			addCriterion("ACC_NAME <", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameLessThanOrEqualTo(String value) {
			addCriterion("ACC_NAME <=", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameLike(String value) {
			addCriterion("ACC_NAME like", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameNotLike(String value) {
			addCriterion("ACC_NAME not like", value, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameIn(List<String> values) {
			addCriterion("ACC_NAME in", values, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameNotIn(List<String> values) {
			addCriterion("ACC_NAME not in", values, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameBetween(String value1, String value2) {
			addCriterion("ACC_NAME between", value1, value2, "accName");
			return (Criteria) this;
		}

		public Criteria andAccNameNotBetween(String value1, String value2) {
			addCriterion("ACC_NAME not between", value1, value2, "accName");
			return (Criteria) this;
		}

		public Criteria andAccTypeIsNull() {
			addCriterion("ACC_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andAccTypeIsNotNull() {
			addCriterion("ACC_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andAccTypeEqualTo(String value) {
			addCriterion("ACC_TYPE =", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeNotEqualTo(String value) {
			addCriterion("ACC_TYPE <>", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeGreaterThan(String value) {
			addCriterion("ACC_TYPE >", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeGreaterThanOrEqualTo(String value) {
			addCriterion("ACC_TYPE >=", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeLessThan(String value) {
			addCriterion("ACC_TYPE <", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeLessThanOrEqualTo(String value) {
			addCriterion("ACC_TYPE <=", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeLike(String value) {
			addCriterion("ACC_TYPE like", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeNotLike(String value) {
			addCriterion("ACC_TYPE not like", value, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeIn(List<String> values) {
			addCriterion("ACC_TYPE in", values, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeNotIn(List<String> values) {
			addCriterion("ACC_TYPE not in", values, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeBetween(String value1, String value2) {
			addCriterion("ACC_TYPE between", value1, value2, "accType");
			return (Criteria) this;
		}

		public Criteria andAccTypeNotBetween(String value1, String value2) {
			addCriterion("ACC_TYPE not between", value1, value2, "accType");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("AMOUNT is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("AMOUNT is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("AMOUNT =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("AMOUNT <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("AMOUNT >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("AMOUNT >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("AMOUNT <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("AMOUNT <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<BigDecimal> values) {
			addCriterion("AMOUNT in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<BigDecimal> values) {
			addCriterion("AMOUNT not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AMOUNT between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("AMOUNT not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("STATUS is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("STATUS is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("STATUS =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("STATUS <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("STATUS >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("STATUS >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("STATUS <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("STATUS <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("STATUS like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("STATUS not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("STATUS in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("STATUS not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("STATUS between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("STATUS not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table pfmsdb_acc
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pfmsdb_acc
     *
     * @mbggenerated do_not_delete_during_merge Sun Mar 15 23:31:22 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}