package com.javaone.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class pfmsExpend {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.VALUE_DATE
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private Date valueDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.TIME_NO
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String timeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.AMOUNT
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private BigDecimal amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.ACC_USAGE1
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String accUsage1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.ACC_USAGE2
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String accUsage2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.ITEM
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String item;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.SHOP
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String shop;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.CREATER_ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private Integer createrId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.CREATE_TIME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.ACC_ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String accId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pfmsdb_expend.REMARK
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.ID
	 * @return  the value of pfmsdb_expend.ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.ID
	 * @param id  the value for pfmsdb_expend.ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.VALUE_DATE
	 * @return  the value of pfmsdb_expend.VALUE_DATE
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public Date getValueDate() {
		return valueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.VALUE_DATE
	 * @param valueDate  the value for pfmsdb_expend.VALUE_DATE
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setValueDate(Date valueDate) {
		this.valueDate = valueDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.TIME_NO
	 * @return  the value of pfmsdb_expend.TIME_NO
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getTimeNo() {
		return timeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.TIME_NO
	 * @param timeNo  the value for pfmsdb_expend.TIME_NO
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setTimeNo(String timeNo) {
		this.timeNo = timeNo == null ? null : timeNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.AMOUNT
	 * @return  the value of pfmsdb_expend.AMOUNT
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.AMOUNT
	 * @param amount  the value for pfmsdb_expend.AMOUNT
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.ACC_USAGE1
	 * @return  the value of pfmsdb_expend.ACC_USAGE1
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getAccUsage1() {
		return accUsage1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.ACC_USAGE1
	 * @param accUsage1  the value for pfmsdb_expend.ACC_USAGE1
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setAccUsage1(String accUsage1) {
		this.accUsage1 = accUsage1 == null ? null : accUsage1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.ACC_USAGE2
	 * @return  the value of pfmsdb_expend.ACC_USAGE2
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getAccUsage2() {
		return accUsage2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.ACC_USAGE2
	 * @param accUsage2  the value for pfmsdb_expend.ACC_USAGE2
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setAccUsage2(String accUsage2) {
		this.accUsage2 = accUsage2 == null ? null : accUsage2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.ITEM
	 * @return  the value of pfmsdb_expend.ITEM
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getItem() {
		return item;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.ITEM
	 * @param item  the value for pfmsdb_expend.ITEM
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setItem(String item) {
		this.item = item == null ? null : item.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.SHOP
	 * @return  the value of pfmsdb_expend.SHOP
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getShop() {
		return shop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.SHOP
	 * @param shop  the value for pfmsdb_expend.SHOP
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setShop(String shop) {
		this.shop = shop == null ? null : shop.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.CREATER_ID
	 * @return  the value of pfmsdb_expend.CREATER_ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public Integer getCreaterId() {
		return createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.CREATER_ID
	 * @param createrId  the value for pfmsdb_expend.CREATER_ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setCreaterId(Integer createrId) {
		this.createrId = createrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.CREATE_TIME
	 * @return  the value of pfmsdb_expend.CREATE_TIME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.CREATE_TIME
	 * @param createTime  the value for pfmsdb_expend.CREATE_TIME
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.ACC_ID
	 * @return  the value of pfmsdb_expend.ACC_ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getAccId() {
		return accId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.ACC_ID
	 * @param accId  the value for pfmsdb_expend.ACC_ID
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setAccId(String accId) {
		this.accId = accId == null ? null : accId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pfmsdb_expend.REMARK
	 * @return  the value of pfmsdb_expend.REMARK
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pfmsdb_expend.REMARK
	 * @param remark  the value for pfmsdb_expend.REMARK
	 * @mbggenerated  Mon Mar 16 21:45:39 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}
}